# Generated by Django 5.0.7 on 2024-08-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='workers/')),
            ],
        ),
    ]
