# Generated by Django 5.0.7 on 2024-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_details', '0002_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
