# Generated by Django 5.0.7 on 2024-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_details', '0005_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='worker',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
